@echo off
REM Minimal config loader. Place secrets in mindos-secrets.properties (KEY=value, # or ; for comments).

set "ROOT_DIR=%~dp0"
set "MINDOS_ENV_LOADED="
set "MINDOS_ENV_STAGE=boot"

if exist "%ROOT_DIR%mindos-secrets.properties" (
  set "MINDOS_ENV_STAGE=loading_secrets"
  for /f "usebackq tokens=1,* delims==" %%A in (`findstr /R /V /C:"^[ ]*[#;]" "%ROOT_DIR%mindos-secrets.properties"`) do (
    if not "%%A"=="" set "%%A=%%B"
  )
)

set "MINDOS_ENV_STAGE=defaults"
if not defined MINDOS_SPRING_PROFILE set "MINDOS_SPRING_PROFILE=solo"
if not defined MINDOS_SERVER_PORT set "MINDOS_SERVER_PORT=8080"
if not defined MINDOS_MEMORY_FILE_REPO_ENABLED set "MINDOS_MEMORY_FILE_REPO_ENABLED=true"
if not defined MINDOS_MEMORY_FILE_REPO_BASE_DIR set "MINDOS_MEMORY_FILE_REPO_BASE_DIR=data/memory-sync"
if not defined MINDOS_PAUSE_ON_EXIT set "MINDOS_PAUSE_ON_EXIT=true"

REM LLM routing profile (override these in mindos-secrets.properties when needed)
if not defined MINDOS_LLM_PROFILE set "MINDOS_LLM_PROFILE=QWEN_STABLE"
if not defined MINDOS_LLM_MODE set "MINDOS_LLM_MODE=QWEN_NATIVE"
if not defined MINDOS_LLM_PROVIDER set "MINDOS_LLM_PROVIDER=qwen"
if not defined MINDOS_LLM_ROUTING_MODE set "MINDOS_LLM_ROUTING_MODE=fixed"
if not defined MINDOS_LLM_ROUTING_STAGE_MAP set "MINDOS_LLM_ROUTING_STAGE_MAP=llm-dsl:qwen,llm-fallback:qwen"
if not defined MINDOS_LLM_ROUTING_PRESET_MAP set "MINDOS_LLM_ROUTING_PRESET_MAP=cost:qwen,balanced:qwen,quality:qwen"
if not defined MINDOS_LLM_ENDPOINT_QWEN set "MINDOS_LLM_ENDPOINT_QWEN=https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
if not defined MINDOS_LLM_ENDPOINT_DOUBAO set "MINDOS_LLM_ENDPOINT_DOUBAO=https://ark.cn-beijing.volces.com/api/v3/chat/completions"
if not defined MINDOS_LLM_ENDPOINT_OPENROUTER set "MINDOS_LLM_ENDPOINT_OPENROUTER=https://openrouter.ai/api/v1/chat/completions"
if not defined MINDOS_LLM_ENDPOINT_OPENAI set "MINDOS_LLM_ENDPOINT_OPENAI=https://api.openai.com/v1/chat/completions"
if not defined MINDOS_LLM_ENDPOINT_GEMINI set "MINDOS_LLM_ENDPOINT_GEMINI=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent"
if not defined MINDOS_LLM_ENDPOINT_GROK set "MINDOS_LLM_ENDPOINT_GROK=https://api.x.ai/v1/chat/completions"
if not defined MINDOS_OPENROUTER_KEY set "MINDOS_OPENROUTER_KEY=REPLACE_WITH_OPENROUTER_KEY"
if not defined MINDOS_OPENAI_KEY set "MINDOS_OPENAI_KEY=REPLACE_WITH_OPENAI_KEY"
if not defined MINDOS_GEMINI_KEY set "MINDOS_GEMINI_KEY=REPLACE_WITH_GEMINI_KEY"
if not defined MINDOS_GROK_KEY set "MINDOS_GROK_KEY=REPLACE_WITH_GROK_KEY"
if not defined MINDOS_QWEN_KEY set "MINDOS_QWEN_KEY=REPLACE_WITH_QWEN_KEY"
if not defined MINDOS_OPENAI_MODEL set "MINDOS_OPENAI_MODEL=gpt-4.1"
if not defined MINDOS_GEMINI_MODEL set "MINDOS_GEMINI_MODEL=gemini-2.5-pro"
if not defined MINDOS_GROK_MODEL set "MINDOS_GROK_MODEL=grok-4"
if not defined MINDOS_QWEN_MODEL set "MINDOS_QWEN_MODEL=qwen3.5-plus"
if not defined MINDOS_DOUBAO_ARK_KEY set "MINDOS_DOUBAO_ARK_KEY=REPLACE_WITH_DOUBAO_ARK_KEY"
if not defined MINDOS_DOUBAO_ENDPOINT_ID set "MINDOS_DOUBAO_ENDPOINT_ID=REPLACE_WITH_DOUBAO_ENDPOINT_ID"
if not defined MINDOS_LLM_PROVIDER_ENDPOINTS set "MINDOS_LLM_PROVIDER_ENDPOINTS=gpt:https://openrouter.ai/api/v1/chat/completions,grok:https://openrouter.ai/api/v1/chat/completions,gemini:https://openrouter.ai/api/v1/chat/completions"
if not defined MINDOS_LLM_PROVIDER_KEYS set "MINDOS_LLM_PROVIDER_KEYS=gpt:%MINDOS_OPENROUTER_KEY%,grok:%MINDOS_OPENROUTER_KEY%,gemini:%MINDOS_OPENROUTER_KEY%,doubao:%MINDOS_DOUBAO_ARK_KEY%,qwen:%MINDOS_QWEN_KEY%"
if not defined MINDOS_LLM_PROVIDER_MODELS set "MINDOS_LLM_PROVIDER_MODELS=gpt:openai/gpt-5.2,grok:x-ai/grok-4,gemini:google/gemini-2.5-pro,doubao:%MINDOS_DOUBAO_ENDPOINT_ID%,qwen:%MINDOS_QWEN_MODEL%"
if not defined MINDOS_SECURITY_METRICS_REQUIRE_ADMIN_TOKEN set "MINDOS_SECURITY_METRICS_REQUIRE_ADMIN_TOKEN=false"
set "MINDOS_INTENT_ROUTING_EXPLICIT="
if defined MINDOS_DISPATCHER_INTENT_ROUTING_ENABLED set "MINDOS_INTENT_ROUTING_EXPLICIT=1"
if not defined MINDOS_DISPATCHER_INTENT_ROUTING_ENABLED set "MINDOS_DISPATCHER_INTENT_ROUTING_ENABLED=false"
if not defined MINDOS_DISPATCHER_SKILL_PRE_ANALYZE_MODE set "MINDOS_DISPATCHER_SKILL_PRE_ANALYZE_MODE=never"

REM Optional IM credentials (leave blank to disable)
if not defined MINDOS_IM_ENABLED set "MINDOS_IM_ENABLED=true"
if not defined MINDOS_IM_DINGTALK_ENABLED set "MINDOS_IM_DINGTALK_ENABLED=true"
if not defined MINDOS_IM_DINGTALK_VERIFY_SIGNATURE set "MINDOS_IM_DINGTALK_VERIFY_SIGNATURE=false"
if not defined MINDOS_IM_DINGTALK_REPLY_TIMEOUT_MS set "MINDOS_IM_DINGTALK_REPLY_TIMEOUT_MS=2500"
if not defined MINDOS_IM_DINGTALK_REPLY_MAX_CHARS set "MINDOS_IM_DINGTALK_REPLY_MAX_CHARS=1200"
if not defined MINDOS_IM_DINGTALK_STREAM_CLIENT_ID set "MINDOS_IM_DINGTALK_STREAM_CLIENT_ID="
if not defined MINDOS_IM_DINGTALK_STREAM_CLIENT_SECRET set "MINDOS_IM_DINGTALK_STREAM_CLIENT_SECRET="
if not defined MINDOS_IM_DINGTALK_STREAM_TOPIC set "MINDOS_IM_DINGTALK_STREAM_TOPIC=/v1.0/im/bot/messages/get"
if not defined MINDOS_IM_DINGTALK_STREAM_WAITING_TEXT set "MINDOS_IM_DINGTALK_STREAM_WAITING_TEXT=已收到，正在处理，稍后给你完整回复。"
if not defined MINDOS_IM_DINGTALK_OUTBOUND_ROBOT_CODE set "MINDOS_IM_DINGTALK_OUTBOUND_ROBOT_CODE="
if not defined MINDOS_IM_DINGTALK_OUTBOUND_APP_KEY set "MINDOS_IM_DINGTALK_OUTBOUND_APP_KEY="
if not defined MINDOS_IM_DINGTALK_OUTBOUND_APP_SECRET set "MINDOS_IM_DINGTALK_OUTBOUND_APP_SECRET="

REM Backward-compatible aliases for older secrets templates.
if defined MINDOS_IM_DINGTALK_APP_KEY if not defined MINDOS_IM_DINGTALK_STREAM_CLIENT_ID set "MINDOS_IM_DINGTALK_STREAM_CLIENT_ID=%MINDOS_IM_DINGTALK_APP_KEY%"
if defined MINDOS_IM_DINGTALK_APP_SECRET if not defined MINDOS_IM_DINGTALK_STREAM_CLIENT_SECRET set "MINDOS_IM_DINGTALK_STREAM_CLIENT_SECRET=%MINDOS_IM_DINGTALK_APP_SECRET%"
if defined MINDOS_IM_DINGTALK_APP_KEY if not defined MINDOS_IM_DINGTALK_OUTBOUND_APP_KEY set "MINDOS_IM_DINGTALK_OUTBOUND_APP_KEY=%MINDOS_IM_DINGTALK_APP_KEY%"
if defined MINDOS_IM_DINGTALK_APP_SECRET if not defined MINDOS_IM_DINGTALK_OUTBOUND_APP_SECRET set "MINDOS_IM_DINGTALK_OUTBOUND_APP_SECRET=%MINDOS_IM_DINGTALK_APP_SECRET%"

REM Reuse stream credentials for outbound unless explicit outbound overrides are provided.
if not defined MINDOS_IM_DINGTALK_OUTBOUND_APP_KEY if defined MINDOS_IM_DINGTALK_STREAM_CLIENT_ID set "MINDOS_IM_DINGTALK_OUTBOUND_APP_KEY=%MINDOS_IM_DINGTALK_STREAM_CLIENT_ID%"
if not defined MINDOS_IM_DINGTALK_OUTBOUND_APP_SECRET if defined MINDOS_IM_DINGTALK_STREAM_CLIENT_SECRET set "MINDOS_IM_DINGTALK_OUTBOUND_APP_SECRET=%MINDOS_IM_DINGTALK_STREAM_CLIENT_SECRET%"

REM Auto-enable stream mode when the required secrets are present.
if not defined MINDOS_IM_DINGTALK_STREAM_ENABLED set "MINDOS_IM_DINGTALK_STREAM_ENABLED=false"
if /I "%MINDOS_IM_DINGTALK_STREAM_ENABLED%"=="false" if defined MINDOS_IM_DINGTALK_STREAM_CLIENT_ID if defined MINDOS_IM_DINGTALK_STREAM_CLIENT_SECRET set "MINDOS_IM_DINGTALK_STREAM_ENABLED=true"

REM Auto-enable outbound delivery when the required values are present.
if not defined MINDOS_IM_DINGTALK_OUTBOUND_ENABLED set "MINDOS_IM_DINGTALK_OUTBOUND_ENABLED=false"
if /I "%MINDOS_IM_DINGTALK_OUTBOUND_ENABLED%"=="false" if defined MINDOS_IM_DINGTALK_OUTBOUND_ROBOT_CODE if defined MINDOS_IM_DINGTALK_OUTBOUND_APP_KEY if defined MINDOS_IM_DINGTALK_OUTBOUND_APP_SECRET set "MINDOS_IM_DINGTALK_OUTBOUND_ENABLED=true"

REM Provider profile switch (manual and predictable)
if /I "%MINDOS_LLM_PROFILE%"=="DOUBAO_STABLE" (
  set "MINDOS_LLM_MODE=DOUBAO_NATIVE"
  set "MINDOS_LLM_PROVIDER=doubao"
  if not defined MINDOS_INTENT_ROUTING_EXPLICIT set "MINDOS_DISPATCHER_INTENT_ROUTING_ENABLED=false"
  set "MINDOS_LLM_ROUTING_STAGE_MAP=llm-dsl:doubao,llm-fallback:doubao"
  set "MINDOS_LLM_ROUTING_PRESET_MAP=cost:doubao,balanced:doubao,quality:doubao"
  set "MINDOS_LLM_PROVIDER_ENDPOINTS=doubao:%MINDOS_LLM_ENDPOINT_DOUBAO%"
  set "MINDOS_LLM_PROVIDER_KEYS=doubao:%MINDOS_DOUBAO_ARK_KEY%"
  set "MINDOS_LLM_PROVIDER_MODELS=doubao:%MINDOS_DOUBAO_ENDPOINT_ID%"
)
if /I "%MINDOS_LLM_PROFILE%"=="QWEN_STABLE" (
  set "MINDOS_LLM_MODE=QWEN_NATIVE"
  set "MINDOS_LLM_PROVIDER=qwen"
  if not defined MINDOS_INTENT_ROUTING_EXPLICIT set "MINDOS_DISPATCHER_INTENT_ROUTING_ENABLED=false"
  set "MINDOS_LLM_ROUTING_STAGE_MAP=llm-dsl:qwen,llm-fallback:qwen"
  set "MINDOS_LLM_ROUTING_PRESET_MAP=cost:qwen,balanced:qwen,quality:qwen"
  set "MINDOS_LLM_PROVIDER_ENDPOINTS=qwen:%MINDOS_LLM_ENDPOINT_QWEN%"
  set "MINDOS_LLM_PROVIDER_KEYS=qwen:%MINDOS_QWEN_KEY%"
  set "MINDOS_LLM_PROVIDER_MODELS=qwen:%MINDOS_QWEN_MODEL%"
)
if /I "%MINDOS_LLM_PROFILE%"=="CN_DUAL" (
  set "MINDOS_LLM_MODE=CN_DUAL_NATIVE"
  set "MINDOS_LLM_PROVIDER=qwen"
  if not defined MINDOS_INTENT_ROUTING_EXPLICIT set "MINDOS_DISPATCHER_INTENT_ROUTING_ENABLED=false"
  set "MINDOS_LLM_ROUTING_STAGE_MAP=llm-dsl:qwen,llm-fallback:doubao"
  set "MINDOS_LLM_ROUTING_PRESET_MAP=cost:qwen,balanced:qwen,quality:doubao"
  set "MINDOS_LLM_PROVIDER_ENDPOINTS=qwen:%MINDOS_LLM_ENDPOINT_QWEN%,doubao:%MINDOS_LLM_ENDPOINT_DOUBAO%"
  set "MINDOS_LLM_PROVIDER_KEYS=qwen:%MINDOS_QWEN_KEY%,doubao:%MINDOS_DOUBAO_ARK_KEY%"
  set "MINDOS_LLM_PROVIDER_MODELS=qwen:%MINDOS_QWEN_MODEL%,doubao:%MINDOS_DOUBAO_ENDPOINT_ID%"
)
if /I "%MINDOS_LLM_PROFILE%"=="OPENROUTER_INTENT" (
  set "MINDOS_LLM_MODE=OPENROUTER"
  set "MINDOS_LLM_PROVIDER=gpt"
  if not defined MINDOS_INTENT_ROUTING_EXPLICIT set "MINDOS_DISPATCHER_INTENT_ROUTING_ENABLED=true"
  set "MINDOS_LLM_PROVIDER_ENDPOINTS=gpt:%MINDOS_LLM_ENDPOINT_OPENROUTER%,grok:%MINDOS_LLM_ENDPOINT_OPENROUTER%,gemini:%MINDOS_LLM_ENDPOINT_OPENROUTER%"
  set "MINDOS_LLM_PROVIDER_KEYS=gpt:%MINDOS_OPENROUTER_KEY%,grok:%MINDOS_OPENROUTER_KEY%,gemini:%MINDOS_OPENROUTER_KEY%"
  set "MINDOS_LLM_PROVIDER_MODELS=gpt:openai/gpt-5.2,grok:x-ai/grok-4,gemini:google/gemini-2.5-pro"
)
if /I "%MINDOS_LLM_PROFILE%"=="OPENAI_NATIVE" (
  set "MINDOS_LLM_MODE=OPENAI_NATIVE"
  set "MINDOS_LLM_PROVIDER=openai"
  if not defined MINDOS_INTENT_ROUTING_EXPLICIT set "MINDOS_DISPATCHER_INTENT_ROUTING_ENABLED=false"
  set "MINDOS_LLM_ROUTING_STAGE_MAP=llm-dsl:openai,llm-fallback:openai"
  set "MINDOS_LLM_ROUTING_PRESET_MAP=cost:openai,balanced:openai,quality:openai"
  set "MINDOS_LLM_PROVIDER_ENDPOINTS=openai:%MINDOS_LLM_ENDPOINT_OPENAI%"
  set "MINDOS_LLM_PROVIDER_KEYS=openai:%MINDOS_OPENAI_KEY%"
  set "MINDOS_LLM_PROVIDER_MODELS=openai:%MINDOS_OPENAI_MODEL%"
)
if /I "%MINDOS_LLM_PROFILE%"=="GEMINI_NATIVE" (
  set "MINDOS_LLM_MODE=GEMINI_NATIVE"
  set "MINDOS_LLM_PROVIDER=gemini"
  if not defined MINDOS_INTENT_ROUTING_EXPLICIT set "MINDOS_DISPATCHER_INTENT_ROUTING_ENABLED=false"
  set "MINDOS_LLM_ROUTING_STAGE_MAP=llm-dsl:gemini,llm-fallback:gemini"
  set "MINDOS_LLM_ROUTING_PRESET_MAP=cost:gemini,balanced:gemini,quality:gemini"
  set "MINDOS_LLM_PROVIDER_ENDPOINTS=gemini:%MINDOS_LLM_ENDPOINT_GEMINI%"
  set "MINDOS_LLM_PROVIDER_KEYS=gemini:%MINDOS_GEMINI_KEY%"
  set "MINDOS_LLM_PROVIDER_MODELS=gemini:%MINDOS_GEMINI_MODEL%"
)
if /I "%MINDOS_LLM_PROFILE%"=="GROK_NATIVE" (
  set "MINDOS_LLM_MODE=GROK_NATIVE"
  set "MINDOS_LLM_PROVIDER=grok"
  if not defined MINDOS_INTENT_ROUTING_EXPLICIT set "MINDOS_DISPATCHER_INTENT_ROUTING_ENABLED=false"
  set "MINDOS_LLM_ROUTING_STAGE_MAP=llm-dsl:grok,llm-fallback:grok"
  set "MINDOS_LLM_ROUTING_PRESET_MAP=cost:grok,balanced:grok,quality:grok"
  set "MINDOS_LLM_PROVIDER_ENDPOINTS=grok:%MINDOS_LLM_ENDPOINT_GROK%"
  set "MINDOS_LLM_PROVIDER_KEYS=grok:%MINDOS_GROK_KEY%"
  set "MINDOS_LLM_PROVIDER_MODELS=grok:%MINDOS_GROK_MODEL%"
)

set "MINDOS_ENV_STAGE=done"
set "MINDOS_ENV_LOADED=1"

