#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
source "$ROOT_DIR/scripts/unix/lib/mindos-env.sh"

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/unix/export/export-mindos-secrets.sh [--force] [--template local|release|dist] [output-file]

Examples:
  ./scripts/unix/export/export-mindos-secrets.sh --template local ./config/secrets/mindos-secrets.local.properties

  export MINDOS_OPENROUTER_KEY=sk-or-xxxx
  ./scripts/unix/export/export-mindos-secrets.sh --template release ./config/secrets/mindos-secrets.release.properties

  ./scripts/unix/export/export-mindos-secrets.sh --template dist ./dist/mindos-windows-server/mindos-secrets.properties
USAGE
}

normalize_template_kind() {
  local raw="${1:-}"
  local upper
  upper="$(printf '%s' "$raw" | tr '[:lower:]-' '[:upper:]_')"
  case "$upper" in
    LOCAL)
      printf 'local'
      ;;
    RELEASE)
      printf 'release'
      ;;
    DIST|RUNTIME|DEFAULT|GENERIC|WINDOWS_DIST)
      printf 'dist'
      ;;
    *)
      return 1
      ;;
  esac
}

detect_template_kind() {
  local output_file="${1:-}"
  case "$(basename "$output_file")" in
    mindos-secrets.local.properties)
      printf 'local'
      ;;
    mindos-secrets.release.properties)
      printf 'release'
      ;;
    mindos-secrets.properties)
      printf 'dist'
      ;;
    *)
      printf 'dist'
      ;;
  esac
}

default_preset_for_template() {
  case "${1:-dist}" in
    local)
      printf 'LOCAL_QWEN'
      ;;
    release|dist)
      printf 'OPENROUTER_INTENT'
      ;;
    *)
      printf 'OPENROUTER_INTENT'
      ;;
  esac
}

emit_template_header() {
  case "${1:-dist}" in
    local)
      cat <<'EOF'
# Generated by scripts/unix/export/export-mindos-secrets.sh using the local template.
# Local override file loaded after dist/mindos-windows-server/mindos-secrets.properties by scripts/unix/local/run.sh --mode=local.
# Edit only the values on the right side. Blank values stay disabled until you fill them.
EOF
      ;;
    release)
      cat <<'EOF'
# Generated by scripts/unix/export/export-mindos-secrets.sh using the release template.
# Release override file loaded by scripts/unix/local/run.sh --mode=release with strict preset validation.
# Edit only the values on the right side. Blank values stay disabled until you fill them.
EOF
      ;;
    *)
      cat <<'EOF'
# Generated by scripts/unix/export/export-mindos-secrets.sh using the dist template.
# Standalone secrets file for dist/install directories such as dist/mindos-windows-server/mindos-secrets.properties.
# Edit only the values on the right side. Blank values stay disabled until you fill them.
EOF
      ;;
  esac
}

emit_provider_endpoint_section() {
  cat <<'EOF'

# Optional provider endpoint overrides
MINDOS_LLM_ENDPOINT_OPENROUTER=https://openrouter.ai/api/v1/chat/completions
MINDOS_LLM_ENDPOINT_QWEN=https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
MINDOS_LLM_ENDPOINT_DOUBAO=https://ark.cn-beijing.volces.com/api/v3/chat/completions
MINDOS_LLM_ENDPOINT_OPENAI=https://api.openai.com/v1/chat/completions
MINDOS_LLM_ENDPOINT_GEMINI=https://generativelanguage.googleapis.com/v1beta/openai/chat/completions
MINDOS_LLM_ENDPOINT_GROK=https://api.x.ai/v1/chat/completions
EOF
}

emit_native_provider_section() {
  local template_kind="${1:-dist}"
  local include_openai="${2:-false}"
  local include_gemini="${3:-false}"
  local include_grok="${4:-false}"
  local force_active="false"

  if [[ "$template_kind" == "dist" ]]; then
    force_active="true"
  fi

  cat <<EOF

# Optional native-provider shortcuts
EOF

  if [[ "$force_active" == "true" || "$include_openai" == "true" ]]; then
    cat <<EOF
MINDOS_OPENAI_KEY=${MINDOS_OPENAI_KEY:-}
MINDOS_OPENAI_MODEL=${MINDOS_OPENAI_MODEL:-gpt-4.1}
EOF
  else
    cat <<'EOF'
# MINDOS_OPENAI_KEY=
# MINDOS_OPENAI_MODEL=gpt-4.1
EOF
  fi

  if [[ "$force_active" == "true" || "$include_gemini" == "true" ]]; then
    cat <<EOF
MINDOS_GEMINI_KEY=${MINDOS_GEMINI_KEY:-}
MINDOS_GEMINI_MODEL=${MINDOS_GEMINI_MODEL:-gemini-2.5-pro}
EOF
  else
    cat <<'EOF'
# MINDOS_GEMINI_KEY=
# MINDOS_GEMINI_MODEL=gemini-2.5-pro
EOF
  fi

  if [[ "$force_active" == "true" || "$include_grok" == "true" ]]; then
    cat <<EOF
MINDOS_GROK_KEY=${MINDOS_GROK_KEY:-}
MINDOS_GROK_MODEL=${MINDOS_GROK_MODEL:-grok-4}
EOF
  else
    cat <<'EOF'
# MINDOS_GROK_KEY=
# MINDOS_GROK_MODEL=grok-4
EOF
  fi
}

emit_dist_search_examples() {
  if [[ "${1:-dist}" != "dist" ]]; then
    return 0
  fi

  cat <<'EOF'
# Examples:
# MINDOS_SKILLS_SEARCH_SOURCES=serper:https://google.serper.dev/search;news-url=https://google.serper.dev/news;api-key=YOUR_SERPER_KEY
# MINDOS_SKILLS_MCP_SERVERS=qwensearch:https://dashscope.aliyuncs.com/api/v1/mcps/WebSearch/mcp
# MINDOS_SKILLS_MCP_SERVER_HEADERS=qwensearch:Authorization=Bearer YOUR_DASHSCOPE_KEY
EOF
}

emit_custom_map_examples() {
  cat <<'EOF'
# Example manual local/cloud mix:
# MINDOS_LLM_PROVIDER_ENDPOINTS=local:http://localhost:11434/api/chat,qwen:https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
# MINDOS_LLM_PROVIDER_KEYS=qwen:sk-xxxx
# MINDOS_LLM_PROVIDER_MODELS=local:gemma3:1b-it-q4_K_M,qwen:qwen3.6-plus
# MINDOS_LLM_ROUTING_STAGE_MAP=llm-dsl:local,llm-fallback:qwen
# MINDOS_LLM_ROUTING_PRESET_MAP=cost:local,balanced:local,quality:qwen
EOF
}

FORCE=false
TEMPLATE_KIND=""
OUTPUT_FILE="$PWD/mindos-secrets.properties"
POSITIONAL=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force)
      FORCE=true
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    --template)
      if [[ $# -lt 2 ]]; then
        echo "[ERROR] --template requires a value: local, release, or dist"
        exit 1
      fi
      shift
      TEMPLATE_KIND="$1"
      ;;
    --template=*)
      TEMPLATE_KIND="${1#*=}"
      ;;
    -*)
      echo "[ERROR] Unknown option: $1"
      usage
      exit 1
      ;;
    *)
      POSITIONAL+=("$1")
      ;;
  esac
  shift
done

if [[ ${#POSITIONAL[@]} -gt 1 ]]; then
  echo "[ERROR] Too many positional arguments."
  usage
  exit 1
fi

if [[ ${#POSITIONAL[@]} -eq 1 ]]; then
  OUTPUT_FILE="${POSITIONAL[0]}"
fi

if [[ -n "$TEMPLATE_KIND" ]]; then
  if ! TEMPLATE_KIND="$(normalize_template_kind "$TEMPLATE_KIND")"; then
    echo "[ERROR] Unsupported template: $TEMPLATE_KIND"
    echo "        Supported templates: local, release, dist"
    exit 1
  fi
fi

OUTPUT_FILE="$(python3 - <<'PY' "$OUTPUT_FILE"
import os
import sys

print(os.path.abspath(sys.argv[1]))
PY
)"

OUTPUT_DIR="$(dirname "$OUTPUT_FILE")"
mkdir -p "$OUTPUT_DIR"

if [[ -e "$OUTPUT_FILE" && "$FORCE" != "true" ]]; then
  echo "[ERROR] Output file already exists: $OUTPUT_FILE"
  echo "        Re-run with --force to overwrite it."
  exit 1
fi

if [[ -z "$TEMPLATE_KIND" ]]; then
  TEMPLATE_KIND="$(detect_template_kind "$OUTPUT_FILE")"
fi

DEFAULT_PRESET="$(default_preset_for_template "$TEMPLATE_KIND")"
SELECTED_PRESET="${MINDOS_MODEL_PRESET:-${MINDOS_LLM_PROFILE:-$DEFAULT_PRESET}}"
CANONICAL_PRESET="$(mindos_canonical_model_preset "$SELECTED_PRESET")"
if [[ -z "$CANONICAL_PRESET" ]]; then
  CANONICAL_PRESET="$(mindos_canonical_model_preset "$DEFAULT_PRESET")"
fi

DISPLAY_PRESET="$CANONICAL_PRESET"
if [[ "$DISPLAY_PRESET" == "CUSTOM_LOCAL_FIRST" ]]; then
  DISPLAY_PRESET="LOCAL_QWEN"
fi

INCLUDE_OPENAI=false
INCLUDE_GEMINI=false
INCLUDE_GROK=false

if [[ -n "${MINDOS_OPENAI_KEY:-}" || -n "${MINDOS_OPENAI_MODEL:-}" || "$CANONICAL_PRESET" == "OPENAI_NATIVE" ]]; then
  INCLUDE_OPENAI=true
fi
if [[ -n "${MINDOS_GEMINI_KEY:-}" || -n "${MINDOS_GEMINI_MODEL:-}" || "$CANONICAL_PRESET" == "GEMINI_NATIVE" ]]; then
  INCLUDE_GEMINI=true
fi
if [[ -n "${MINDOS_GROK_KEY:-}" || -n "${MINDOS_GROK_MODEL:-}" || "$CANONICAL_PRESET" == "GROK_NATIVE" ]]; then
  INCLUDE_GROK=true
fi

{
  emit_template_header "$TEMPLATE_KIND"

  cat <<EOF
MINDOS_SPRING_PROFILE=${MINDOS_SPRING_PROFILE:-solo}
MINDOS_MODEL_PRESET=$DISPLAY_PRESET

# Common presets:
# OPENROUTER_INTENT - OpenRouter primary, optional Qwen fallback
# QWEN_STABLE       - Qwen primary
# DOUBAO_STABLE     - Doubao primary
# LOCAL_QWEN        - local endpoint primary, optional Qwen fallback
# CN_DUAL           - China cloud dual-provider preset
# OPENAI_NATIVE / GEMINI_NATIVE / GROK_NATIVE - native-provider shortcuts
# CUSTOM            - advanced manual maps below
MINDOS_OPENROUTER_KEY=${MINDOS_OPENROUTER_KEY:-}
MINDOS_QWEN_KEY=${MINDOS_QWEN_KEY:-}
MINDOS_QWEN_MODEL=${MINDOS_QWEN_MODEL:-qwen3.6-plus}
MINDOS_DOUBAO_ARK_KEY=${MINDOS_DOUBAO_ARK_KEY:-}
MINDOS_DOUBAO_ENDPOINT_ID=${MINDOS_DOUBAO_ENDPOINT_ID:-}
MINDOS_LOCAL_LLM_ENDPOINT=${MINDOS_LOCAL_LLM_ENDPOINT:-http://localhost:11434/api/chat}
MINDOS_LOCAL_LLM_MODEL=${MINDOS_LOCAL_LLM_MODEL:-gemma3:1b-it-q4_K_M}
EOF

  emit_provider_endpoint_section "$TEMPLATE_KIND"

  emit_native_provider_section "$TEMPLATE_KIND" "$INCLUDE_OPENAI" "$INCLUDE_GEMINI" "$INCLUDE_GROK"

  cat <<EOF

# Optional search + MCP integrations
MINDOS_SKILLS_SEARCH_SOURCES=${MINDOS_SKILLS_SEARCH_SOURCES:-}
MINDOS_SKILLS_MCP_SERVERS=${MINDOS_SKILLS_MCP_SERVERS:-}
MINDOS_SKILLS_MCP_SERVER_HEADERS=${MINDOS_SKILLS_MCP_SERVER_HEADERS:-}
EOF

  emit_dist_search_examples "$TEMPLATE_KIND"

  cat <<EOF

# Optional DingTalk stream credentials
MINDOS_IM_DINGTALK_STREAM_CLIENT_ID=${MINDOS_IM_DINGTALK_STREAM_CLIENT_ID:-}
MINDOS_IM_DINGTALK_STREAM_CLIENT_SECRET=${MINDOS_IM_DINGTALK_STREAM_CLIENT_SECRET:-}
MINDOS_IM_DINGTALK_OUTBOUND_ROBOT_CODE=${MINDOS_IM_DINGTALK_OUTBOUND_ROBOT_CODE:-}

# Safe defaults
MINDOS_DISPATCHER_SEMANTIC_ANALYSIS_LOCAL_ESCALATION_ENABLED=${MINDOS_DISPATCHER_SEMANTIC_ANALYSIS_LOCAL_ESCALATION_ENABLED:-false}
MINDOS_DISPATCHER_LOCAL_ESCALATION_ENABLED=${MINDOS_DISPATCHER_LOCAL_ESCALATION_ENABLED:-false}

# Advanced manual maps for MINDOS_MODEL_PRESET=CUSTOM only
EOF

  emit_custom_map_examples

  cat <<EOF
# MINDOS_LLM_PROVIDER_ENDPOINTS=
# MINDOS_LLM_PROVIDER_KEYS=
# MINDOS_LLM_PROVIDER_MODELS=
# MINDOS_LLM_ROUTING_STAGE_MAP=
# MINDOS_LLM_ROUTING_PRESET_MAP=
EOF
} > "$OUTPUT_FILE"

echo "[INFO] Wrote $OUTPUT_FILE"
echo "[INFO] Template: $TEMPLATE_KIND"
case "$CANONICAL_PRESET" in
  OPENROUTER_INTENT)
    if mindos_is_blank_or_placeholder "${MINDOS_OPENROUTER_KEY:-}"; then
      echo "[INFO] Fill MINDOS_OPENROUTER_KEY before strict release startup."
    fi
    ;;
  QWEN_STABLE)
    if mindos_is_blank_or_placeholder "${MINDOS_QWEN_KEY:-}"; then
      echo "[INFO] Fill MINDOS_QWEN_KEY before strict release startup."
    fi
    ;;
  DOUBAO_STABLE)
    if mindos_is_blank_or_placeholder "${MINDOS_DOUBAO_ARK_KEY:-}" || mindos_is_blank_or_placeholder "${MINDOS_DOUBAO_ENDPOINT_ID:-}"; then
      echo "[INFO] Fill MINDOS_DOUBAO_ARK_KEY and MINDOS_DOUBAO_ENDPOINT_ID before strict release startup."
    fi
    ;;
  CUSTOM_LOCAL_FIRST)
    if mindos_is_blank_or_placeholder "${MINDOS_LOCAL_LLM_ENDPOINT:-}" || mindos_is_blank_or_placeholder "${MINDOS_LOCAL_LLM_MODEL:-}"; then
      echo "[INFO] Confirm the local endpoint/model values before strict release startup."
    fi
    ;;
  OPENAI_NATIVE)
    if mindos_is_blank_or_placeholder "${MINDOS_OPENAI_KEY:-}"; then
      echo "[INFO] Fill MINDOS_OPENAI_KEY before strict release startup."
    fi
    ;;
  GEMINI_NATIVE)
    if mindos_is_blank_or_placeholder "${MINDOS_GEMINI_KEY:-}"; then
      echo "[INFO] Fill MINDOS_GEMINI_KEY before strict release startup."
    fi
    ;;
  GROK_NATIVE)
    if mindos_is_blank_or_placeholder "${MINDOS_GROK_KEY:-}"; then
      echo "[INFO] Fill MINDOS_GROK_KEY before strict release startup."
    fi
    ;;
esac
