#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
source "$ROOT_DIR/scripts/unix/lib/mindos-env.sh"

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/unix/export/export-mindos-secrets.sh [--force] [output-file]

Examples:
  export MINDOS_MODEL_PRESET=OPENROUTER_INTENT
  export MINDOS_OPENROUTER_KEY=sk-or-xxxx
  ./scripts/unix/export/export-mindos-secrets.sh ./mindos-secrets.properties

  export MINDOS_MODEL_PRESET=LOCAL_QWEN
  export MINDOS_LOCAL_LLM_ENDPOINT=http://localhost:11434/api/chat
  export MINDOS_LOCAL_LLM_MODEL=gemma3:1b-it-q4_K_M
  ./scripts/unix/export/export-mindos-secrets.sh --force ./mindos-secrets.properties
USAGE
}

FORCE=false
OUTPUT_FILE="$PWD/mindos-secrets.properties"
POSITIONAL=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force)
      FORCE=true
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    -*)
      echo "[ERROR] Unknown option: $1"
      usage
      exit 1
      ;;
    *)
      POSITIONAL+=("$1")
      ;;
  esac
  shift
done

if [[ ${#POSITIONAL[@]} -gt 1 ]]; then
  echo "[ERROR] Too many positional arguments."
  usage
  exit 1
fi

if [[ ${#POSITIONAL[@]} -eq 1 ]]; then
  OUTPUT_FILE="${POSITIONAL[0]}"
fi

OUTPUT_FILE="$(python3 - <<'PY' "$OUTPUT_FILE"
import os
import sys

print(os.path.abspath(sys.argv[1]))
PY
)"

OUTPUT_DIR="$(dirname "$OUTPUT_FILE")"
mkdir -p "$OUTPUT_DIR"

if [[ -e "$OUTPUT_FILE" && "$FORCE" != "true" ]]; then
  echo "[ERROR] Output file already exists: $OUTPUT_FILE"
  echo "        Re-run with --force to overwrite it."
  exit 1
fi

SELECTED_PRESET="${MINDOS_MODEL_PRESET:-${MINDOS_LLM_PROFILE:-OPENROUTER_INTENT}}"
CANONICAL_PRESET="$(mindos_canonical_model_preset "$SELECTED_PRESET")"
if [[ -z "$CANONICAL_PRESET" ]]; then
  CANONICAL_PRESET="OPENROUTER_INTENT"
fi

DISPLAY_PRESET="$CANONICAL_PRESET"
if [[ "$DISPLAY_PRESET" == "CUSTOM_LOCAL_FIRST" ]]; then
  DISPLAY_PRESET="LOCAL_QWEN"
fi

INCLUDE_OPENAI=false
INCLUDE_GEMINI=false
INCLUDE_GROK=false

if [[ -n "${MINDOS_OPENAI_KEY:-}" || -n "${MINDOS_OPENAI_MODEL:-}" || "$CANONICAL_PRESET" == "OPENAI_NATIVE" ]]; then
  INCLUDE_OPENAI=true
fi
if [[ -n "${MINDOS_GEMINI_KEY:-}" || -n "${MINDOS_GEMINI_MODEL:-}" || "$CANONICAL_PRESET" == "GEMINI_NATIVE" ]]; then
  INCLUDE_GEMINI=true
fi
if [[ -n "${MINDOS_GROK_KEY:-}" || -n "${MINDOS_GROK_MODEL:-}" || "$CANONICAL_PRESET" == "GROK_NATIVE" ]]; then
  INCLUDE_GROK=true
fi

{
  cat <<EOF
# Generated by scripts/unix/export/export-mindos-secrets.sh
# Edit only the values on the right side. Blank values stay disabled until you fill them.

MINDOS_SPRING_PROFILE=${MINDOS_SPRING_PROFILE:-solo}
MINDOS_MODEL_PRESET=$DISPLAY_PRESET

# Common presets:
# OPENROUTER_INTENT - OpenRouter primary, optional Qwen fallback
# QWEN_STABLE       - Qwen primary
# DOUBAO_STABLE     - Doubao primary
# LOCAL_QWEN        - local endpoint primary, optional Qwen fallback
# CUSTOM            - advanced manual maps below
MINDOS_OPENROUTER_KEY=${MINDOS_OPENROUTER_KEY:-}
MINDOS_QWEN_KEY=${MINDOS_QWEN_KEY:-}
MINDOS_QWEN_MODEL=${MINDOS_QWEN_MODEL:-qwen3.6-plus}
MINDOS_DOUBAO_ARK_KEY=${MINDOS_DOUBAO_ARK_KEY:-}
MINDOS_DOUBAO_ENDPOINT_ID=${MINDOS_DOUBAO_ENDPOINT_ID:-}
MINDOS_LOCAL_LLM_ENDPOINT=${MINDOS_LOCAL_LLM_ENDPOINT:-http://localhost:11434/api/chat}
MINDOS_LOCAL_LLM_MODEL=${MINDOS_LOCAL_LLM_MODEL:-gemma3:1b-it-q4_K_M}
EOF

  if [[ "$INCLUDE_OPENAI" == "true" ]]; then
    cat <<EOF
MINDOS_OPENAI_KEY=${MINDOS_OPENAI_KEY:-}
MINDOS_OPENAI_MODEL=${MINDOS_OPENAI_MODEL:-gpt-4.1}
EOF
  fi

  if [[ "$INCLUDE_GEMINI" == "true" ]]; then
    cat <<EOF
MINDOS_GEMINI_KEY=${MINDOS_GEMINI_KEY:-}
MINDOS_GEMINI_MODEL=${MINDOS_GEMINI_MODEL:-gemini-2.5-pro}
EOF
  fi

  if [[ "$INCLUDE_GROK" == "true" ]]; then
    cat <<EOF
MINDOS_GROK_KEY=${MINDOS_GROK_KEY:-}
MINDOS_GROK_MODEL=${MINDOS_GROK_MODEL:-grok-4}
EOF
  fi

  cat <<EOF

# Optional search + MCP integrations
MINDOS_SKILLS_SEARCH_SOURCES=${MINDOS_SKILLS_SEARCH_SOURCES:-}
MINDOS_SKILLS_MCP_SERVERS=${MINDOS_SKILLS_MCP_SERVERS:-}
MINDOS_SKILLS_MCP_SERVER_HEADERS=${MINDOS_SKILLS_MCP_SERVER_HEADERS:-}

# Optional DingTalk stream credentials
MINDOS_IM_DINGTALK_STREAM_CLIENT_ID=${MINDOS_IM_DINGTALK_STREAM_CLIENT_ID:-}
MINDOS_IM_DINGTALK_STREAM_CLIENT_SECRET=${MINDOS_IM_DINGTALK_STREAM_CLIENT_SECRET:-}
MINDOS_IM_DINGTALK_OUTBOUND_ROBOT_CODE=${MINDOS_IM_DINGTALK_OUTBOUND_ROBOT_CODE:-}

# Safe defaults
MINDOS_DISPATCHER_SEMANTIC_ANALYSIS_LOCAL_ESCALATION_ENABLED=${MINDOS_DISPATCHER_SEMANTIC_ANALYSIS_LOCAL_ESCALATION_ENABLED:-false}
MINDOS_DISPATCHER_LOCAL_ESCALATION_ENABLED=${MINDOS_DISPATCHER_LOCAL_ESCALATION_ENABLED:-false}

# Advanced manual maps for MINDOS_MODEL_PRESET=CUSTOM only
# MINDOS_LLM_PROVIDER_ENDPOINTS=
# MINDOS_LLM_PROVIDER_KEYS=
# MINDOS_LLM_PROVIDER_MODELS=
# MINDOS_LLM_ROUTING_STAGE_MAP=
# MINDOS_LLM_ROUTING_PRESET_MAP=
EOF
} > "$OUTPUT_FILE"

echo "[INFO] Wrote $OUTPUT_FILE"
case "$CANONICAL_PRESET" in
  OPENROUTER_INTENT)
    if mindos_is_blank_or_placeholder "${MINDOS_OPENROUTER_KEY:-}"; then
      echo "[INFO] Fill MINDOS_OPENROUTER_KEY before strict release startup."
    fi
    ;;
  QWEN_STABLE)
    if mindos_is_blank_or_placeholder "${MINDOS_QWEN_KEY:-}"; then
      echo "[INFO] Fill MINDOS_QWEN_KEY before strict release startup."
    fi
    ;;
  DOUBAO_STABLE)
    if mindos_is_blank_or_placeholder "${MINDOS_DOUBAO_ARK_KEY:-}" || mindos_is_blank_or_placeholder "${MINDOS_DOUBAO_ENDPOINT_ID:-}"; then
      echo "[INFO] Fill MINDOS_DOUBAO_ARK_KEY and MINDOS_DOUBAO_ENDPOINT_ID before strict release startup."
    fi
    ;;
  CUSTOM_LOCAL_FIRST)
    if mindos_is_blank_or_placeholder "${MINDOS_LOCAL_LLM_ENDPOINT:-}" || mindos_is_blank_or_placeholder "${MINDOS_LOCAL_LLM_MODEL:-}"; then
      echo "[INFO] Confirm the local endpoint/model values before strict release startup."
    fi
    ;;
  OPENAI_NATIVE)
    if mindos_is_blank_or_placeholder "${MINDOS_OPENAI_KEY:-}"; then
      echo "[INFO] Fill MINDOS_OPENAI_KEY before strict release startup."
    fi
    ;;
  GEMINI_NATIVE)
    if mindos_is_blank_or_placeholder "${MINDOS_GEMINI_KEY:-}"; then
      echo "[INFO] Fill MINDOS_GEMINI_KEY before strict release startup."
    fi
    ;;
  GROK_NATIVE)
    if mindos_is_blank_or_placeholder "${MINDOS_GROK_KEY:-}"; then
      echo "[INFO] Fill MINDOS_GROK_KEY before strict release startup."
    fi
    ;;
esac
